// Catálogo de papel higiénico (datos de ejemplo inspirados en el catálogo de referencia)
export const productos = [
  {
    id: 'jr-ultra-basic-400',
    nombre: 'Jumbo Roll Scott Ultra Basic 1P 1*400',
    categoria: 'Jumbo Roll',
    presentacion: 'Caja 4 rollos · 400 mts',
    precio: 189.0,
    imagen: '/producto-jumbo.png',
    etiqueta: 'Institucional',
  },
  {
    id: 'jr-ultra-basic-500',
    nombre: 'Jumbo Roll Scott Ultra Basic 1*500',
    categoria: 'Jumbo Roll',
    presentacion: 'Caja 8 rollos · 500 mts',
    precio: 349.0,
    imagen: '/producto-jumbo.png',
    etiqueta: 'Más vendido',
  },
  {
    id: 'jr-scott-500',
    nombre: 'Jumbo Roll Scott 6*1*500 Mts.',
    categoria: 'Jumbo Roll',
    presentacion: 'Caja 6 rollos · 500 mts',
    precio: 275.0,
    imagen: '/producto-jumbo.png',
    etiqueta: null,
  },
  {
    id: 'center-pull-twins',
    nombre: 'Jumbo Center Pull Twins 1*230',
    categoria: 'Center Pull',
    presentacion: 'Rollo · 230 mts',
    precio: 65.0,
    imagen: '/producto-centerpull.png',
    etiqueta: null,
  },
  {
    id: 'center-pull-320',
    nombre: 'Jumbo Center Pull 6*1*320 mts',
    categoria: 'Center Pull',
    presentacion: 'Caja 6 rollos · 320 mts',
    precio: 210.0,
    imagen: '/producto-centerpull.png',
    etiqueta: null,
  },
  {
    id: 'scott-plus-2h',
    nombre: 'Papel Higiénico Scott Plus 2H 24*200',
    categoria: 'Hogar',
    presentacion: 'Fardo 24 rollos · 200 hojas',
    precio: 145.0,
    imagen: '/producto-pack.png',
    etiqueta: 'Doble hoja',
  },
  {
    id: 'scott-esencias',
    nombre: 'Papel Higiénico Scott Esencias 1*12',
    categoria: 'Hogar',
    presentacion: 'Paquete 12 rollos',
    precio: 78.0,
    imagen: '/producto-pack.png',
    etiqueta: null,
  },
  {
    id: 'scott-rinde-max',
    nombre: 'Papel Higiénico Scott Rinde Max 24*1*420',
    categoria: 'Hogar',
    presentacion: 'Fardo 24 rollos · 420 hojas',
    precio: 168.0,
    imagen: '/producto-pack.png',
    etiqueta: 'Rendidor',
  },
  {
    id: 'kleenex-aroma',
    nombre: 'Papel Hig. Kleenex 2H C/Aroma 24*1*450',
    categoria: 'Hogar',
    presentacion: 'Fardo 24 rollos · 450 hojas',
    precio: 182.0,
    imagen: '/producto-pack.png',
    etiqueta: 'Con aroma',
  },
  {
    id: 'mini-jrt-150',
    nombre: 'Mini JRT Scott 24*150 Mts.',
    categoria: 'Mini JRT',
    presentacion: 'Caja 24 rollos · 150 mts',
    precio: 320.0,
    imagen: '/producto-jumbo.png',
    etiqueta: null,
  },
  {
    id: 'eco-blanco-400',
    nombre: 'Jumbo Roll Eco Blanco 400 mts.',
    categoria: 'Jumbo Roll',
    presentacion: 'Rollo · 400 mts',
    precio: 42.0,
    imagen: '/producto-jumbo.png',
    etiqueta: 'Económico',
  },
  {
    id: 'bulkpack-scott',
    nombre: 'Bulkpack Scott 2H 36*126',
    categoria: 'Hogar',
    presentacion: 'Fardo 36 rollos · 126 hojas',
    precio: 205.0,
    imagen: '/producto-pack.png',
    etiqueta: null,
  },
]

export const categorias = ['Todos', 'Jumbo Roll', 'Center Pull', 'Mini JRT', 'Hogar']

